package smvDebugger.condition;

/*Generated by MPS */

import java.util.Map;

public class Disjunction extends BinaryExpression {
  public Disjunction(final Expression first, final Expression second) {
    super(first, second);
  }

  @Override
  public boolean evaluate(final Map<String, String> stepValues) {
    return first.evaluate(stepValues) || second.evaluate(stepValues);
  }
}
