package smvDebugger.condition;

/*Generated by MPS */

import java.util.Map;
import java.util.Objects;

public class Equality extends BinaryExpression {
  public Equality(final Expression first, final Expression second) {
    super(first, second);
    if (!((first instanceof Argument)) || !((second instanceof Argument))) {
      throw new IllegalArgumentException("Unexpected type of args");
    }
  }

  @Override
  public boolean evaluate(final Map<String, String> stepValues) {
    final Argument name = (Argument) first;
    final Argument value = (Argument) second;
    return Objects.equals(stepValues.get(name.getContent()), value.getContent());
  }
}
