package smvDebugger.condition;

/*Generated by MPS */

import java.util.Map;

public class Inequality extends BinaryExpression {
  public Inequality(final Expression firsr, final Expression second) {
    super(firsr, second);
  }

  @Override
  public boolean evaluate(final Map<String, String> stepValues) {
    return first.evaluate(stepValues) && second.evaluate(stepValues);
  }
}
