package org.fbme.debugger.plugin

import jetbrains.mps.openapi.editor.extensions.EditorExtensionRegistry
import jetbrains.mps.plugins.part.ProjectPluginPart
import jetbrains.mps.project.MPSProject
import org.fbme.ide.richediting.inspections.InspectionManagerImpl

/*Generated by MPS */
class InspectionsManager_ProjectPluginPart : ProjectPluginPart() {
    override fun init(project: MPSProject) {
        val reg = project.getComponent(EditorExtensionRegistry::class.java)
        reg.registerExtension(InspectionManagerImpl.EDITOR_EXTENSION)
    }

    override fun dispose(project: MPSProject) {
        val reg = project.getComponent(EditorExtensionRegistry::class.java)
        reg.unregisterExtension(InspectionManagerImpl.EDITOR_EXTENSION)
    }
}
