package smvDebugger.main;

/*Generated by MPS */

import javax.swing.JComponent;
import jetbrains.mps.project.MPSProject;
import org.fbme.lib.iec61499.declarations.CompositeFBTypeDeclaration;
import java.nio.file.Path;
import smvDebugger.fb2smv.Fb2SmvIntegration;
import java.util.Optional;
import smvDebugger.nusmv.Counterexample;
import smvDebugger.nusmv.NuSmvIntegration;
import smvDebugger.panel.DebugPanel;
import java.io.FileFilter;
import java.io.File;
import java.util.Objects;
import javax.swing.JOptionPane;

public class SmvDebugger {
  private static final String FB_FILE_EXTENSION = ".xml";

  public static JComponent run(final MPSProject project, final CompositeFBTypeDeclaration fb) {
    final Path fbPath = getFbPath(project, fb);
    final Path smvPath = Fb2SmvIntegration.convertFbToSmv(fbPath);
    final String specification = getSpecification();

    final Optional<Counterexample> counterexample = NuSmvIntegration.getCounterexample(smvPath, specification);
    if (counterexample.isEmpty()) {
      notifySuccess();
      return null;
    }
    return DebugPanel.run(project, fb, counterexample.get());
  }

  private static Path getFbPath(final MPSProject project, final CompositeFBTypeDeclaration fb) {
    return project.getProjectFile().listFiles(new FileFilter() {
      public boolean accept(final File it) {
        return Objects.equals(it.getName(), fb.getName() + FB_FILE_EXTENSION);
      }
    })[0].toPath();
  }

  private static String getSpecification() {
    final String specification = JOptionPane.showInputDialog(null, "Enter LTL specification");
    return specification;
  }

  private static void notifySuccess() {
    JOptionPane.showMessageDialog(null, "Success");
  }
}
