package smvDebugger.panel.mvc;

/*Generated by MPS */

import javax.swing.SpinnerModel;
import javax.swing.table.TableModel;
import javax.swing.ListSelectionModel;
import javax.swing.BoundedRangeModel;
import smvDebugger.model.Counterexample;
import javax.swing.SpinnerListModel;
import smvDebugger.common.ArrayUtils;
import javax.swing.DefaultListSelectionModel;
import javax.swing.DefaultBoundedRangeModel;

public class DebugPanelModel {
  private static final String FIRST_COLUMN_NAME = "Components/States";

  private final SpinnerModel stepModel;
  private final GlobalTimeModel globalTimeModel;
  private final TableModel dataModel;
  private final ListSelectionModel dataSelectionModel;
  private final BoundedRangeModel dataScrollModel;

  public DebugPanelModel(final Counterexample counterexample) {
    stepModel = new SpinnerListModel();
    globalTimeModel = new GlobalTimeModel();

    dataModel = new UneditableTableModel(ArrayUtils.concat(counterexample.getItems(), counterexample.getValues()), ArrayUtils.concat(FIRST_COLUMN_NAME, counterexample.getStates()));
    dataSelectionModel = new DefaultListSelectionModel();
    dataSelectionModel.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

    dataScrollModel = new DefaultBoundedRangeModel();
  }

  public SpinnerModel getStepModel() {
    return stepModel;
  }

  public GlobalTimeModel getGlobalTimeModel() {
    return globalTimeModel;
  }

  public TableModel getDataModel() {
    return dataModel;
  }

  public ListSelectionModel getDataSelectionModel() {
    return dataSelectionModel;
  }

  public BoundedRangeModel getDataScrollModel() {
    return dataScrollModel;
  }
}
