package smvDebugger.commons;

/*Generated by MPS */

import junit.framework.TestCase;
import junit.framework.Assert;
import java.util.Arrays;

public class ArrayUtils_Test extends TestCase {
  public void test_toArray() throws Exception {
    Assert.assertTrue(Arrays.equals(new Object[]{1}, ArrayUtils.toArray(1)));
  }
  public void test_to2dArray() throws Exception {
    final Object[][] result = ArrayUtils.to2dArray(new Object[]{1, 2});
    Assert.assertTrue(Arrays.equals(new Object[]{1}, result[0]));
    Assert.assertTrue(Arrays.equals(new Object[]{2}, result[1]));
  }
  public void test_concatObjects() throws Exception {
    Assert.assertTrue(Arrays.equals(new Object[]{1, 2, 3}, ArrayUtils.concat(1, new Object[]{2, 3})));
  }
  public void test_concatStrings() throws Exception {
    Assert.assertTrue(Arrays.equals(new String[]{"1", "2", "3"}, ArrayUtils.concat(new String[]{"1", "2"}, "3")));
  }
  public void test_subarray() throws Exception {
    Assert.assertTrue(Arrays.equals(new String[]{"2", "3"}, ArrayUtils.subarray(new String[]{"1", "2", "3", "4"}, 1, 3)));
  }
}
