package smvDebugger.commons;

/*Generated by MPS */

import java.util.List;
import smvDebugger.visualization.HiglhightObject;
import smvDebugger.nusmv.VariableData;
import java.util.ArrayList;

public class CommonUtils {
  public static Object[] concat(Object obj, Object[] objects) {
    Object[] result = new Object[objects.length + 1];
    result[0] = obj;
    System.arraycopy(objects, 0, result, 1, objects.length);
    return result;
  }

  public static List<HiglhightObject> toHiglightObjectList(final VariableData[] vars, final int stateIndex) {
    final List<HiglhightObject> objects = new ArrayList<HiglhightObject>();
    for (final VariableData var : vars) {
      objects.add(new HiglhightObject(var.fbName(), var.portName(), var.getValue(stateIndex), var.isECC()));
    }
    //  
    return objects;
  }

  public static String[][] to2dArray(final List<List<String>> listOfLists) {
    final String[][] array = new String[listOfLists.size()][];

    for (int i = 0; i < array.length; i++) {
      final List<String> list = listOfLists.get(i);
      array[i] = new String[list.size()];
      for (int j = 0; j < array[i].length; j++) {
        array[i][j] = list.get(j);
      }
    }

    return array;
  }
}
