package smvDebugger.panel.items;

/*Generated by MPS */

import javax.swing.JPanel;
import smvDebugger.panel.mvc.DebugPanelMVCItem;
import smvDebugger.panel.mvc.DebugPanelModel;

public class ControlPanel extends JPanel implements DebugPanelMVCItem {
  @Override
  public void setModel(final DebugPanelModel model) {
  }

  @Override
  public void initView() {
  }

  @Override
  public void initController() {
  }
}
