package smvDebugger.panel.items;

/*Generated by MPS */

import javax.swing.JPanel;
import smvDebugger.panel.mvc.DebugPanelMVCItem;
import java.awt.Color;
import javax.swing.JTable;
import javax.swing.JScrollBar;
import javax.swing.JScrollPane;
import smvDebugger.model.Counterexample;
import smvDebugger.visualization.BacktraceService;
import smvDebugger.visualization.SystemHighlighter;
import smvDebugger.panel.mvc.DebugPanelModel;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableColumn;
import javax.swing.ScrollPaneConstants;
import java.awt.Dimension;
import java.beans.PropertyChangeListener;
import java.beans.PropertyChangeEvent;
import java.util.Objects;
import javax.swing.event.ListSelectionListener;
import javax.swing.event.ListSelectionEvent;
import smvDebugger.model.SystemItemValue;
import java.util.List;
import javax.swing.event.ChangeListener;
import javax.swing.event.ChangeEvent;
import javax.swing.JViewport;

public class CounterexampleTable extends JPanel implements DebugPanelMVCItem {
  private static final Color DEFAULT_CELL_COLOR = Color.WHITE;
  private static final Color HIGHLIGHT_CELL_COLOR = Color.GREEN;
  private static final int COLUMN_WIDTH = 80;
  private static final int FIRST_COLUMN_WIDTH = 360;
  private static final int SCROLL_PANE_WIDTH = 780;
  private static final int SCROLL_PANE_HEIGHT = 360;
  private static final String MODEL_NAME = "model";
  private static final String SELECTION_MODEL_NAME = "selectionModel";

  private final HighlightedTable valueTable = new HighlightedTable();
  private final JTable itemTable = new JTable();
  private final JScrollBar horizontalScrollBar = new JScrollBar(JScrollBar.HORIZONTAL);
  private final JScrollPane scrollPane = new JScrollPane();

  private final Counterexample counterexample;
  private final BacktraceService backtraceService;
  private final SystemHighlighter systemHighlighter;

  public CounterexampleTable(final Counterexample counterexample, final BacktraceService backtraceService, final SystemHighlighter systemHighlighter) {
    this.counterexample = counterexample;
    this.backtraceService = backtraceService;
    this.systemHighlighter = systemHighlighter;
  }

  @Override
  public void setModel(final DebugPanelModel model) {
    valueTable.setModel(model.getDataModel());
    valueTable.setSelectionModel(model.getDataSelectionModel());

    itemTable.setModel(valueTable.getModel());
    itemTable.setSelectionModel(valueTable.getSelectionModel());
    final TableColumnModel columnModel = valueTable.getColumnModel();
    final TableColumn column = columnModel.getColumn(0);
    columnModel.removeColumn(column);
    itemTable.getColumnModel().addColumn(column);

    horizontalScrollBar.setModel(model.getDataScrollModel());
  }

  @Override
  public void initView() {
    valueTable.setAutoCreateColumnsFromModel(false);
    valueTable.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
    final TableColumnModel mainTableColumnModel = valueTable.getColumnModel();
    for (int i = 0; i < mainTableColumnModel.getColumnCount(); i++) {
      mainTableColumnModel.getColumn(i).setPreferredWidth(COLUMN_WIDTH);
    }
    valueTable.setCellSelectionEnabled(true);
    valueTable.setDefaultCellColor(DEFAULT_CELL_COLOR);
    valueTable.setHighlightCellColor(HIGHLIGHT_CELL_COLOR);

    itemTable.setAutoCreateColumnsFromModel(false);
    itemTable.getColumnModel().getColumn(0).setPreferredWidth(FIRST_COLUMN_WIDTH);
    itemTable.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
    itemTable.setPreferredScrollableViewportSize(itemTable.getPreferredSize());
    itemTable.setRowSelectionAllowed(false);
    itemTable.setColumnSelectionAllowed(false);
    itemTable.setFocusable(false);

    scrollPane.setViewportView(valueTable);
    scrollPane.setHorizontalScrollBar(horizontalScrollBar);
    scrollPane.setRowHeaderView(itemTable);
    scrollPane.setCorner(JScrollPane.UPPER_LEFT_CORNER, itemTable.getTableHeader());
    scrollPane.setHorizontalScrollBarPolicy(ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
    scrollPane.setVerticalScrollBarPolicy(ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
    scrollPane.setPreferredSize(new Dimension(SCROLL_PANE_WIDTH, SCROLL_PANE_HEIGHT));

    add(scrollPane);
  }

  @Override
  public void initController() {
    valueTable.addPropertyChangeListener(new PropertyChangeListener() {
      public void propertyChange(final PropertyChangeEvent event) {
        if (Objects.equals(event.getPropertyName(), MODEL_NAME)) {
          itemTable.setModel(valueTable.getModel());
        }
        if (Objects.equals(event.getPropertyName(), SELECTION_MODEL_NAME)) {
          itemTable.setSelectionModel(valueTable.getSelectionModel());
        }
      }
    });
    valueTable.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
      public void valueChanged(final ListSelectionEvent event) {
        final int itemIndex = valueTable.getSelectedRow();
        final int stateIndex = valueTable.getSelectedColumn();

        final SystemItemValue itemValue = counterexample.getItemValue(itemIndex, stateIndex);
        final List<String> relatedItemSimpleNames = backtraceService.getRelatedItemSimpleNames(itemValue);
        final List<SystemItemValue> relatedItems = counterexample.getItemValues(relatedItemSimpleNames, stateIndex);
        systemHighlighter.highlight(relatedItems);

      }
    });

    scrollPane.getRowHeader().addChangeListener(new ChangeListener() {
      public void stateChanged(final ChangeEvent event) {
        final JViewport viewport = (JViewport) event.getSource();
        scrollPane.getVerticalScrollBar().setValue(viewport.getViewPosition().y);
      }
    });
  }
}
