package smvDebugger.panel.items;

/*Generated by MPS */

import javax.swing.JPanel;
import smvDebugger.panel.mvc.DebugPanelMVCItem;
import smvDebugger.model.Counterexample;
import smvDebugger.visualization.BacktraceService;
import smvDebugger.visualization.SystemHighlighter;
import smvDebugger.panel.mvc.DebugPanelModel;
import java.awt.BorderLayout;

public class DebugPanel extends JPanel implements DebugPanelMVCItem {
  private final ControlPanel controlPanel;
  private final CounterexampleTable counterexampleTable;

  public DebugPanel(final Counterexample counterexample, final BacktraceService backtraceService, final SystemHighlighter systemHighlighter) {
    controlPanel = new ControlPanel();
    counterexampleTable = new CounterexampleTable(counterexample, backtraceService, systemHighlighter);
  }

  @Override
  public void setModel(final DebugPanelModel model) {
    controlPanel.setModel(model);
    counterexampleTable.setModel(model);
  }

  @Override
  public void initView() {
    setLayout(new BorderLayout());
    add(controlPanel, BorderLayout.WEST);
    add(counterexampleTable, BorderLayout.CENTER);

    controlPanel.initView();
    counterexampleTable.initView();
  }

  @Override
  public void initController() {
    controlPanel.initController();
    counterexampleTable.initController();
  }
}
