package smvDebugger.panel.items;

/*Generated by MPS */

import javax.swing.JPanel;
import smvDebugger.panel.mvc.DebugPanelMVCItem;
import smvDebugger.panel.mvc.DebugPanelModel;
import smvDebugger.model.Counterexample;
import smvDebugger.visualization.SystemHighlighter;
import smvDebugger.visualization.BacktraceService;
import java.awt.BorderLayout;

public class DebugPanel extends JPanel implements DebugPanelMVCItem {
  private final ControlPanel controlPanel;
  private final CounterexampleTable counterexampleTable;

  private DebugPanelModel model;

  public DebugPanel(final Counterexample counterexample, final SystemHighlighter systemHighlighter, final BacktraceService backtraceService) {
    controlPanel = new ControlPanel(counterexample, systemHighlighter);
    counterexampleTable = new CounterexampleTable(counterexample, systemHighlighter, backtraceService);
  }

  @Override
  public void setPanelModel(final DebugPanelModel model) {
    this.model = model;
    controlPanel.setPanelModel(model);
    counterexampleTable.setPanelModel(model);
  }

  @Override
  public void initView() {
    controlPanel.initView();
    counterexampleTable.initView();

    setLayout(new BorderLayout());
    add(controlPanel, BorderLayout.WEST);
    add(counterexampleTable, BorderLayout.CENTER);
  }

  @Override
  public void initController() {
    controlPanel.initController();
    counterexampleTable.initController();
  }
}
