package smvDebugger.panel.items;

/*Generated by MPS */

import javax.swing.JLabel;
import smvDebugger.panel.mvc.DebugPanelMVCItem;
import smvDebugger.panel.mvc.GlobalTimeModel;
import smvDebugger.panel.mvc.DebugPanelModel;
import java.beans.PropertyChangeListener;
import java.beans.PropertyChangeEvent;

public class GlobalTime extends JLabel implements DebugPanelMVCItem {
  private GlobalTimeModel globalTimeModel;

  @Override
  public void setModel(final DebugPanelModel model) {
    globalTimeModel = model.getGlobalTimeModel();
  }

  @Override
  public void initView() {
  }

  @Override
  public void initController() {
    globalTimeModel.addPropertyChangeListener(GlobalTimeModel.TIME, new PropertyChangeListener() {
      public void propertyChange(final PropertyChangeEvent event) {
        final String time = (String) event.getNewValue();
        setText(time);
      }
    });
  }
}
