package smvDebugger.panel.items;

/*Generated by MPS */

import javax.swing.JLabel;
import smvDebugger.panel.mvc.DebugPanelMVCItem;
import smvDebugger.panel.mvc.DebugPanelModel;
import smvDebugger.panel.mvc.GlobalTimeModel;
import java.beans.PropertyChangeListener;
import java.beans.PropertyChangeEvent;

public class GlobalTime extends JLabel implements DebugPanelMVCItem {
  private static final String LEFT_PADDING = "     ";
  private DebugPanelModel model;

  @Override
  public void setPanelModel(final DebugPanelModel model) {
    this.model = model;
  }

  @Override
  public void initView() {
  }

  @Override
  public void initController() {
    model.getGlobalTimeModel().addPropertyChangeListener(GlobalTimeModel.GLOBAL_TIME, new PropertyChangeListener() {
      public void propertyChange(final PropertyChangeEvent event) {
        final String time = (String) event.getNewValue();
        setText(LEFT_PADDING + time);
      }
    });
  }
}
