package smvDebugger.panel.items;

/*Generated by MPS */

import javax.swing.JTable;
import java.awt.Color;
import java.awt.Component;
import javax.swing.table.TableCellRenderer;
import java.util.Objects;

public class HighlightedTable extends JTable {
  private Color defaultCellColor = Color.WHITE;
  private Color highlightCellColor = Color.GREEN;

  public Color getDefaultCellColor() {
    return defaultCellColor;
  }

  public void setDefaultCellColor(final Color defaultCellColor) {
    this.defaultCellColor = defaultCellColor;
  }

  public Color getHighlightCellColor() {
    return highlightCellColor;
  }

  public void setHighlightCellColor(final Color hightlightCellColor) {
    this.highlightCellColor = hightlightCellColor;
  }

  @Override
  public Component prepareRenderer(final TableCellRenderer renderer, final int rowIndex, final int columnIndex) {
    final Component component = super.prepareRenderer(renderer, rowIndex, columnIndex);
    if (!(Objects.equals(component.getBackground(), getSelectionBackground()))) {
      Color color = defaultCellColor;

      if (columnIndex > 1) {
        final String curValue = (String) getValueAt(rowIndex, columnIndex);
        final String prevValue = (String) getValueAt(rowIndex, columnIndex - 1);

        if (!(Objects.equals(curValue, prevValue))) {
          color = highlightCellColor;
        }
      }

      component.setBackground(color);
      color = null;
    }
    return component;
  }
}
