package smvDebugger.panel.items;

/*Generated by MPS */

import javax.swing.JSpinner;

public class HorizontalSpinner extends JSpinner {
  public HorizontalSpinner() {
    super();
    setUI(new HorizontalSpinnerUI());
  }
}
