package smvDebugger.integration;

/*Generated by MPS */

import java.nio.file.Path;
import smvDebugger.common.OSUtils;

public class NutracService extends AbstractIntegrationService {
  public static final String NUTRAC_FILE_EXTENSION = "nutrac";
  private static final String NUTRAC_EXE_PATH = "Library/FB2SMV/nutrac.exe";
  private static final String CSV_FILE_EXTENSION = "csv";

  public Path convertToCsv(final Path rawCounterexamplePath) {
    runProcess(rawCounterexamplePath);
    return newPathOf(rawCounterexamplePath, CSV_FILE_EXTENSION);
  }

  @Override
  protected String getCommand(final Path counterexamplePath) {
    switch (OSUtils.getOS()) {
      case MAC_OS:
        return MAC_MONO_FRAMEWORK + " " + NUTRAC_EXE_PATH + " " + counterexamplePath.toString();
      default:
        return "";
    }
  }
}
