package smvDebugger.plugin;

/*Generated by MPS */

import jetbrains.mps.plugins.tool.GeneratedTool;
import javax.swing.Icon;
import smvDebugger.main.SmvDebugger;
import jetbrains.mps.project.MPSProject;
import org.fbme.lib.iec61499.declarations.CompositeFBTypeDeclaration;
import com.intellij.openapi.project.Project;
import com.intellij.openapi.wm.ToolWindowAnchor;
import javax.swing.JComponent;

public class Debug_SMV_Tool extends GeneratedTool {
  private static final Icon ICON = null;
  private SmvDebugger smvDebugger = new SmvDebugger();
  private MPSProject project;
  private CompositeFBTypeDeclaration compositeFB;
  public Debug_SMV_Tool(Project project) {
    super(project, "Debug SMV", null, ICON, ToolWindowAnchor.BOTTOM, false);
  }
  /*package*/ void setProject(final MPSProject project) {
    Debug_SMV_Tool.this.project = project;
  }
  /*package*/ void setCompositeFB(final CompositeFBTypeDeclaration compositeFB) {
    Debug_SMV_Tool.this.compositeFB = compositeFB;
  }
  public JComponent getComponent() {
    return Debug_SMV_Tool.this.smvDebugger.run(Debug_SMV_Tool.this.project, Debug_SMV_Tool.this.compositeFB);
  }
}
