package smvDebugger.visualization;

/*Generated by MPS */


public class HiglhightedItem {
  private final String fbName;
  private final String portName;
  private final String value;
  private final boolean ecc;

  public HiglhightedItem(final String fbName, final String portName, final String value, final boolean ecc) {
    this.fbName = fbName;
    this.portName = portName;
    this.value = value;
    this.ecc = ecc;
  }

  public String getFbName() {
    return fbName;
  }

  public String getPortName() {
    return portName;
  }

  public String getValue() {
    return value;
  }

  public boolean isECC() {
    return ecc;
  }
}
