package smvDebugger.visualization;

/*Generated by MPS */


public class HiglhightObject {
  private final String fbName;
  private final String portName;
  private final String value;
  private final boolean isECC;

  public HiglhightObject(final String fbName, final String portName, final String value, final boolean isECC) {
    this.fbName = fbName;
    this.portName = portName;
    this.value = value;
    this.isECC = isECC;
  }

  public String fbName() {
    return fbName;
  }

  public String portName() {
    return portName;
  }

  public String value() {
    return value;
  }

  public boolean isECC() {
    return isECC;
  }
}
