package smvDebugger.visualization;

/*Generated by MPS */

import javax.swing.JPanel;
import jetbrains.mps.project.MPSProject;
import org.fbme.lib.iec61499.declarations.CompositeFBTypeDeclaration;
import smvDebugger.model.Counterexample;
import javax.swing.table.DefaultTableModel;
import javax.swing.JTable;
import javax.swing.JScrollPane;
import java.awt.Dimension;
import javax.swing.BorderFactory;
import java.awt.Color;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableColumn;
import javax.swing.ScrollPaneConstants;
import smvDebugger.model.SystemItem;
import java.util.List;
import smvDebugger.common.ArrayUtils;
import java.util.ArrayList;
import org.fbme.lib.iec61499.fbnetwork.FBNetwork;
import org.fbme.lib.iec61499.fbnetwork.FunctionBlockDeclarationBase;
import org.fbme.lib.iec61499.fbnetwork.FBNetworkConnection;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.internal.collections.runtime.IWhereFilter;
import org.fbme.lib.iec61499.fbnetwork.FunctionBlockDeclaration;
import java.util.Objects;
import java.util.Set;

public class VariableStateTrace extends JPanel {
  private final MPSProject project;
  private final CompositeFBTypeDeclaration compositeFB;
  private final Counterexample counterexample;

  private DefaultTableModel tableModel;
  private JTable table;
  private final JScrollPane scrollPane;
  private int counter = 0;

  public VariableStateTrace(final MPSProject project, final CompositeFBTypeDeclaration compositeFB, final Counterexample counterexample) {
    this.project = project;
    this.compositeFB = compositeFB;
    this.counterexample = counterexample;

    setPreferredSize(new Dimension(300, 200));
    setBorder(BorderFactory.createLineBorder(Color.GRAY));

    tableModel = new DefaultTableModel() {
      @Override
      public boolean isCellEditable(final int row, final int column) {
        return false;
      }
    };

    table = new JTable(tableModel);
    table.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
    table.setTableHeader(null);
    table.setColumnSelectionAllowed(true);
    table.setRowSelectionAllowed(false);

    final TableColumnModel columnModel = table.getColumnModel();
    for (int i = 0; i < columnModel.getColumnCount(); i++) {
      final TableColumn column = columnModel.getColumn(i);
      final int width = 100;
      column.setPreferredWidth(width);
    }

    scrollPane = new JScrollPane(table);
    scrollPane.setVerticalScrollBarPolicy(ScrollPaneConstants.VERTICAL_SCROLLBAR_AS_NEEDED);
    scrollPane.setHorizontalScrollBarPolicy(ScrollPaneConstants.HORIZONTAL_SCROLLBAR_AS_NEEDED);
    scrollPane.setPreferredSize(new Dimension(300, 200));


    add(scrollPane);
  }

  public void updateTrace(final int varIndex, final int stateIndex) {
    final SystemItem var = counterexample.???()[varIndex];
    final List<List<String>> trace = getTrace(var.???(), var.???(), var.???());
    final String[][] data = ArrayUtils.to2dArray(trace);

    tableModel = new DefaultTableModel() {
      @Override
      public boolean isCellEditable(final int row, final int column) {
        return false;
      }
    };
    for (String[] path : data) {
      tableModel.addColumn(null, path);
    }
    table.setModel(tableModel);
    final TableColumnModel columnModel = table.getColumnModel();
    for (int i = 0; i < columnModel.getColumnCount(); i++) {
      final TableColumn column = columnModel.getColumn(i);
      final int width = 260;
      column.setPreferredWidth(width);
    }
  }

  private List<List<String>> getTrace(final String fbName, final String portName, final boolean isVar) {
    final List<List<String>> trace = new ArrayList<List<String>>();
    this.project.getModelAccess().runReadAction(new Runnable() {
      public void run() {
        final FBNetwork fbNethwork = VariableStateTrace.this.compositeFB.getNetwork();
        final List<FunctionBlockDeclarationBase> components = fbNethwork.getContextComponents();
        final List<FBNetworkConnection> connections = fbNethwork.getDataConnections();

        final FunctionBlockDeclarationBase component = ListSequence.fromList(components).findFirst(new IWhereFilter<FunctionBlockDeclarationBase>() {
          public boolean accept(FunctionBlockDeclarationBase it) {
            return it instanceof FunctionBlockDeclaration && Objects.equals(((FunctionBlockDeclaration) it).getName(), fbName);
          }
        });


        if (component instanceof FunctionBlockDeclaration) {
          final FunctionBlockDeclaration blockDeclaration = (FunctionBlockDeclaration) component;
        }
      }
    });
    return trace;
  }

  private void traverse(final Set<FBNetworkConnection> connections, final List<List<String>> traverse) {
  }
}
