package smvDebugger.model;

/*Generated by MPS */

import java.util.Objects;

public class SystemItem {
  public static final String SIMPLE_NAME_DELIMITER = ".";

  private final String fullName;
  private final String fbName;
  private final String itemName;
  private final SystemItemType type;

  public SystemItem(final String fullName, final String fbName, final String itemName, final SystemItemType type) {
    this.fullName = fullName;
    this.fbName = fbName;
    this.itemName = itemName;
    this.type = type;
  }

  public String getFullName() {
    return fullName;
  }

  public String getFbName() {
    return fbName;
  }

  public String getItemName() {
    return itemName;
  }

  public SystemItemType getType() {
    return type;
  }

  public String getSimpleName() {
    return fbName + SIMPLE_NAME_DELIMITER + itemName;
  }

  @Override
  public boolean equals(final Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    final SystemItem item = (SystemItem) o;
    return Objects.equals(fullName, item.fullName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fullName);
  }
}
