package smvDebugger.model;

/*Generated by MPS */


public class SystemItemValue {
  private final SystemItem item;
  private final String value;

  public SystemItemValue(final SystemItem item, final String value) {
    this.item = item;
    this.value = value;
  }

  public SystemItem getItem() {
    return item;
  }

  public String getValue() {
    return value;
  }
}
