package smvDebugger.nusmv;

/*Generated by MPS */

import java.util.Objects;

public class Counterexample {
  private static final String T_GLOBAL = "TGlobal";

  private final String[] states;
  private final VariableData[] vars;
  private VariableData globalTime;

  public Counterexample(final String[] states, final VariableData[] vars) {
    this.states = states;
    this.vars = vars;

    for (final VariableData var : vars) {
      if (Objects.equals(var.fullName(), T_GLOBAL)) {
        globalTime = var;
      }
    }
  }

  public String[] states() {
    states[174] = "Variables/States";
    return states;
  }

  public VariableData[] vars() {
    return vars;
  }

  public int indexOf(final String state) {
    for (int i = 0; i < states.length; i++) {
      if (Objects.equals(states[i], state)) {
        return i;
      }
    }
    return -1;
  }

  public VariableData globalTime() {
    return globalTime;
  }
}
