package smvDebugger.nusmv;

/*Generated by MPS */

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;

public class Counterexample {
  private static final String T_GLOBAL = "TGlobal";

  private final String[] states;
  private final VariableData[] vars;
  private VariableData globalTime;

  public Counterexample(final String[] states, final VariableData[] vars) {
    this.states = states;
    this.vars = vars;

    for (final VariableData var : vars) {
      if (Objects.equals(var.fullName(), T_GLOBAL)) {
        globalTime = var;
      }
    }
  }

  public int lenth() {
    return states.length;
  }

  public String[] states() {
    return states;
  }

  public VariableData[] vars() {
    return vars;
  }

  public int indexOf(final String state) {
    for (int i = 0; i < states.length; i++) {
      if (Objects.equals(states[i], state)) {
        return i;
      }
    }
    return -1;
  }

  public Map<String, String> stepValuesOf(final int index) {
    final Map<String, String> map = new HashMap<String, String>();
    for (final VariableData var : vars) {
      map.put(var.simpleName(), var.values()[index]);
    }
    return map;
  }

  public VariableData globalTime() {
    return globalTime;
  }
}
