package smvDebugger.nusmv;

/*Generated by MPS */

import java.nio.file.Path;

public class NuSmvIntegration {
  public static Path convertFbToSmv(final Path fbPath) {
    final ProcessBuilder builder = new ProcessBuilder();
    builder.command(getCommand());

    final Process process;
    try {
      process = builder.start();
      process.waitFor();
    } catch (final Exception e) {
      throw new RuntimeException(e);
    }

    return <!TextGen not found for 'jetbrains.mps.baseLanguage.structure.Expression'!>;
  }

  private static String getCommand() {
    return "nusmv";
  }
}
