package smvDebugger.plugin;

/*Generated by MPS */

import jetbrains.mps.plugins.prefs.BasePrefsPage;
import javax.swing.Icon;
import com.intellij.openapi.project.Project;
import jetbrains.mps.plugins.prefs.BaseProjectPrefsComponent;
import com.intellij.openapi.options.ConfigurationException;
import javax.swing.JComponent;

public class SmvBinaryPaths_NutracPath_PreferencesPage extends BasePrefsPage {
  private static final Icon ICON = null;

  private PathComponent myComponent;
  public SmvBinaryPaths_NutracPath_PreferencesPage(Project project, BaseProjectPrefsComponent prefsComponent) {
    super(project, prefsComponent);
  }
  public String getDisplayName() {
    return "NutracPath";
  }
  public Icon getIcon() {
    return ICON;
  }
  public boolean isModified() {
    return this.isModified(this.getProject(), this.myComponent);
  }
  public void apply() throws ConfigurationException {
    if (this.myComponent != null) {
      this.commit(this.getProject(), this.myComponent);
    }
  }
  private void commit(Project project, PathComponent component) {
    ((SmvBinaryPaths_PreferencesComponent) SmvBinaryPaths_NutracPath_PreferencesPage.this.getPrefsComponent()).getStateObject().nutracPath = ((PathComponent) component).getValue();
  }
  public JComponent createComponent() {
    if (this.myComponent == null) {
      this.myComponent = new PathComponent("nutrac");
    }
    return this.myComponent;
  }
  private boolean isModified(Project project, PathComponent component) {
    return ((SmvBinaryPaths_PreferencesComponent) SmvBinaryPaths_NutracPath_PreferencesPage.this.getPrefsComponent()).getStateObject().nutracPath != ((PathComponent) component).getValue();
  }
  public void disposeUIResources() {
    this.myComponent = null;
  }
  public void reset() {
    if (this.myComponent != null) {
      this.reset(this.getProject(), this.myComponent);
    }
  }
  private void reset(Project project, PathComponent component) {
    ((PathComponent) component).setValue(((SmvBinaryPaths_PreferencesComponent) SmvBinaryPaths_NutracPath_PreferencesPage.this.getPrefsComponent()).getStateObject().nutracPath);
  }
  @Override
  public String getHelpTopic() {
    return "NutracPath";
  }
}
