package smvDebugger.plugin;

/*Generated by MPS */

import jetbrains.mps.plugins.applicationplugins.BaseApplicationPlugin;
import com.intellij.openapi.extensions.PluginId;
import org.jetbrains.annotations.NotNull;
import org.fbme.ide.richediting.plugin.IEC61499Actions_ActionGroup;

public class SmvDebugger_ApplicationPlugin extends BaseApplicationPlugin {
  private final PluginId myId = PluginId.getId("smvDebugger");

  public SmvDebugger_ApplicationPlugin() {
  }

  @NotNull
  public PluginId getId() {
    return myId;
  }

  public void createGroups() {
    // actions w/o parameters 
    addAction(new Debug_SMV_Action());
    // groups 
    addGroup(new SmvDebuggerGroup_ActionGroup(this));
  }
  public void adjustRegularGroups() {
    insertGroupIntoAnother(SmvDebuggerGroup_ActionGroup.ID, IEC61499Actions_ActionGroup.ID, null);
  }
}
