package smvDebugger.panel.condition;

/*Generated by MPS */


public class ConditionParseException extends RuntimeException {
  public ConditionParseException(final String message) {
    super(message);
  }
}
