package smvDebugger.panel.condition;

/*Generated by MPS */

import java.util.Map;
import java.util.Objects;

public class Equality extends AbstractEquality {
  public Equality(final Expression first, final Expression second) {
    super(first, second);
  }

  @Override
  public boolean evaluate(final Map<String, String> stepValues) {
    if (!((first instanceof Argument))) {
      return first.evaluate(stepValues) == second.evaluate(stepValues);
    }
    final Argument name = (Argument) first;
    final Argument value = (Argument) second;
    return Objects.equals(stepValues.get(name.getContent()), value.getContent());
  }

  @Override
  public String getSymbol() {
    return "==";
  }
}
