package smvDebugger.panel;

/*Generated by MPS */

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

public class CSVFileProvider {
  private static final String DEFAULT_PATH = "/Users/mtereshchuk_s/Desktop/Thesis/FB2SMV-example";
  private static final String FILE_NAME_EXT_DESCRIPTION = "*.csv";
  private static final String FILE_NAME_EXT = "csv";

  public static File getCSVFile() {
    final JFileChooser fileChooser = new JFileChooser(DEFAULT_PATH);
    final FileNameExtensionFilter fileFilter = new FileNameExtensionFilter(FILE_NAME_EXT_DESCRIPTION, FILE_NAME_EXT);
    fileChooser.setFileFilter(fileFilter);
    fileChooser.showOpenDialog(null);
    return fileChooser.getSelectedFile();
  }
}
