package smvDebugger.panel;

/*Generated by MPS */

import jetbrains.mps.project.MPSProject;
import javax.swing.JPanel;
import org.fbme.lib.iec61499.declarations.CompositeFBTypeDeclaration;
import smvDebugger.model.Counterexample;
import smvDebugger.visualization.BacktraceService;
import smvDebugger.visualization.SystemHighlighter;
import smvDebugger.panel.mvc.DebugPanelModel;
import smvDebugger.panel.items.DebugPanel;

public class DebugPanelService {
  private final MPSProject project;

  public DebugPanelService(final MPSProject project) {
    this.project = project;
  }

  public JPanel run(final CompositeFBTypeDeclaration compositeFb, final Counterexample counterexample) {
    final BacktraceService backtraceService = new BacktraceService(project, compositeFb);
    final SystemHighlighter systemHighlighter = new SystemHighlighter(project, compositeFb);
    final DebugPanelModel model = new DebugPanelModel(counterexample);

    final DebugPanel debugPanel = new DebugPanel(counterexample, systemHighlighter, backtraceService);
    debugPanel.setPanelModel(model);
    debugPanel.initView();
    debugPanel.initController();

    return debugPanel;
  }
}
