package smvDebugger.panel;

/*Generated by MPS */

import javax.swing.JPanel;
import javax.swing.JSpinner;
import javax.swing.JLabel;
import smvDebugger.nusmv.Counterexample;
import java.awt.Dimension;
import java.awt.FlowLayout;
import javax.swing.SpinnerModel;
import javax.swing.SpinnerListModel;
import javax.swing.event.ChangeListener;

public class StateChanger extends JPanel {
  private static final int CHANGER_WIDTH = 300;
  private static final int CHANGER_HEIGHT = 70;
  private static final String STEP_LABEL_NAME = "Current step:";
  private static final String TIME_LABEL_NAME = "Current time:";

  private final JSpinner spinner;
  private final JLabel timeValueLabel;

  public StateChanger(final Counterexample counterexample) {
    setPreferredSize(new Dimension(CHANGER_WIDTH, CHANGER_HEIGHT));
    setLayout(new FlowLayout(FlowLayout.LEFT));

    final JLabel stepLabel = new JLabel(STEP_LABEL_NAME);
    final SpinnerModel spinnerModel = new SpinnerListModel(counterexample.states());
    spinner = new JSpinner(spinnerModel);

    final JLabel timeLabel = new JLabel(TIME_LABEL_NAME);
    timeValueLabel = new JLabel("12");

    final JLabel space = new JLabel();
    space.setPreferredSize(new Dimension(30, 10));

    add(stepLabel);
    add(spinner);
    add(space);
    add(timeLabel);
    add(timeValueLabel);

    final JLabel spaceJLabel = new JLabel();
    spaceJLabel.setPreferredSize(new Dimension(150, 10));

    add(spaceJLabel);
    add(new JLabel("Condition:"));
    add(new ConditionNavigator(16));
  }

  public void addChangeListener(final ChangeListener changeListener) {
    spinner.addChangeListener(changeListener);
  }

  public void setTime(final String value) {
    timeValueLabel.setText(value);
  }
}
