package smvDebugger.model;

/*Generated by MPS */

import junit.framework.TestCase;
import junit.framework.Assert;
import java.util.Arrays;

public class SystemItemParser_Test extends TestCase {
  /*package*/ SystemItemParser itemParser;
  public void test_eventPort() throws Exception {
    final SystemItem item = itemParser.parse("rootFb.fb.event_eventPort");
    Assert.assertEquals(SystemItemType.EVENT_PORT, item.getType());
    Assert.assertTrue(Arrays.equals(new String[]{"fb"}, item.getFbNames()));
    Assert.assertEquals("eventPort", item.getItemName());
  }
  public void test_dataPort() throws Exception {
    final SystemItem item = itemParser.parse("rootFb.fb.varPort");
    Assert.assertEquals(SystemItemType.DATA_PORT, item.getType());
    Assert.assertTrue(Arrays.equals(new String[]{"fb"}, item.getFbNames()));
    Assert.assertEquals("varPort", item.getItemName());
  }
  public void test_ecc() throws Exception {
    final SystemItem item = itemParser.parse("rootFb.fb.Q_smv");
    Assert.assertEquals(SystemItemType.ECC, item.getType());
    Assert.assertTrue(Arrays.equals(new String[]{"fb"}, item.getFbNames()));
    Assert.assertEquals("ECC", item.getItemName());
  }
  public void setUp() {
    itemParser = new SystemItemParser();
  }
}
