package smvDebugger.fb2smv;

/*Generated by MPS */

import java.nio.file.Path;
import smvDebugger.commons.OS;
import smvDebugger.commons.OSUtils;

public class Fb2SmvIntegration {
  private static final String MAC_MONO_FRAMEWORK = "mono";
  private static final String FB2SMV_EXE_PATH = "/Library/FB2SMV/CommandShell.exe";
  private static final String SMV_FILE_EXTENSION = "smv";

  public static Path convertFbToSmv(final Path fbPath) {
    final OS os = OSUtils.getOS();
    final ProcessBuilder builder = new ProcessBuilder();
    builder.command(getCommand(os, fbPath));

    final Process process;
    try {
      process = builder.start();
      process.waitFor();
    } catch (final Exception e) {
      throw new RuntimeException(e);
    }

    return getSmvPath(fbPath);
  }

  private static String getCommand(final OS operatingSystem, final Path fbPath) {
    switch (operatingSystem) {
      case MAC_OS:
        return MAC_MONO_FRAMEWORK + " " + FB2SMV_EXE_PATH + " " + fbPath.toString();
      default:
        return "";
    }
  }

  private static Path getSmvPath(final Path fbPath) {
    final String fbFileName = fbPath.getFileName().toString();
    final String fbName = fbFileName.substring(0, fbFileName.lastIndexOf("."));
    final String smvFileName = fbName + "." + SMV_FILE_EXTENSION;
    return fbPath.getParent().resolve(smvFileName);
  }
}
