package smvDebugger.fb2smv;

/*Generated by MPS */

import java.nio.file.Path;
import smvDebugger.commons.OS;
import smvDebugger.commons.OSUtils;

public class NutracIntegration {
  private static final String MAC_MONO_FRAMEWORK = "mono";
  private static final String NUTRAC_EXE_PATH = "Library/FB2SMV/nutrac.exe";

  public static Path convertToCsv(final Path counterexamplePath) {
    final OS os = OSUtils.getOS();

    final ProcessBuilder builder = new ProcessBuilder();
    builder.command(getCommand(os, counterexamplePath));

    final Process process;
    try {
      process = builder.start();
      process.waitFor();
    } catch (final Exception e) {
      throw new RuntimeException(e);
    }

    return Fb2SmvIntegration.getSmvPath(counterexamplePath);
  }

  private static String getCommand(final OS operatingSystem, final Path counterexamplePath) {
    switch (operatingSystem) {
      case MAC_OS:
        return MAC_MONO_FRAMEWORK + " " + NUTRAC_EXE_PATH + " " + counterexamplePath.toString();
      default:
        return "";
    }
  }

  private static Path getSmvPath(final Path fbPath) {
    final String fbFileName = fbPath.getFileName().toString();
    final String fbName = fbFileName.substring(0, fbFileName.lastIndexOf("."));
    final String smvFileName = fbName + "." + Fb2SmvIntegration.SMV_FILE_EXTENSION;
    return fbPath.getParent().resolve(smvFileName);
  }

}
