source "https://rubygems.org"

gem "jekyll"

group :jekyll_plugins do
  gem "jekyll-feed"
  gem "github-pages"
end

platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo"
  gem "tzinfo-data"
end

gem "wdm", :platforms => [:mingw, :x64_mingw, :mswin]

gem "http_parser.rb", :platforms => [:jruby]

gem "webrick"

